server:
  port: 8001

## mybatis配置
#mybatis:
#  type-aliases-package: com.buptse.pojo
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false

# spring配置
spring:
  application:
    name: UTIL-SERVICE-PROVIDER
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://124.70.47.227:3306/dejavu?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: XXXXX
    password: XXXXXXX
  boot:
    admin:
      client:
        url: http://localhost:8888
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:

# Eureka的配置,服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-01.com:7100/eureka,http://eureka-server-01.com:7100/eureka,http://eureka-server-01.com:7100/eureka
  instance:
    instance-id: util-service-provider-8001 # 修改eureka上的默认描述信息

# info配置
info:
  app.name: util.service.provider.8001


management:
  endpoints:
    web:
      exposure:
        include: '*'

