server:
  port: 7200

#Eureka
eureka:
  instance:
    hostname: eureka-server-02.com # Eureka服务端的实例名称
  client:
    register-with-eureka: false # 表示是否向eureka注册中心注册自己
    fetch-registry: false # fetch-registry如果为false,则表示自己为注册中心
    service-url: # 监控页面
      defaultZone: http://eureka-server-01.com:7100/eureka/,http://eureka-server-03.com:7300/eureka/

