server:
  port: 9001

# Eureka配置
eureka:
  client:
    register-with-eureka: false # 不向Eureka注册自己
    service-url:
      defaultZone: http://eureka-server-01.com:7100/eureka,http://eureka-server-02.com:7200/eureka,http://eureka-server-03.com:7300/eureka

## Resilience4j 配置
#resilience4j:
#  # 配置断路器
#  circuitbreaker:
#    circuit-breaker-aspect-order: 398 # 优先级
#    instances:
#      cbA:
#        ringBufferSizeInHalfOpenState: 3 # 当断路器处于 HalfOpen 状态时，环形缓冲区的大小
#        ringBufferSizeInClosedState: 5 # 当断路器处于 Closed 状态时，环形缓冲区的大小
#        waitInterval: 5000
#        recordExceptions:
#          - org.springframework.web.client.HttpServerErrorException # 记录异常
